[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.preDeploy]
commands = [
  "php artisan migrate --force",
  "php artisan db:seed --force",
  "php artisan storage:link"
]

[build.variables]
PHP_VERSION = "8.3"

